#version: "3.9"
#services:
#  backend:
#    image: orozali/medcheck
#    container_name: med-check
#    ports:
#      - "80:2024"
#    restart: always
#    environment:
#      SPRING_PROFILES_ACTIVE: main
#      SERVER_PORT: 2024
#      POSTGRES_DB: medcheck
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: Orozali2003
#  database:
#    image: orozali/postgres
#    restart: always
#    container_name: database
#    ports:
#      - "5432:5433"
#    environment:
#      POSTGRES_DB: medcheck
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: Orozali2003
#    volumes:
#      - db_data:/var/lib/postgresql/data
#volumes:
#  db_data:
#
