#version: '3.8'
#
#services:
#  postgres:
#    image: orozali/postgres
#    build:
#      context: .
#      dockerfile: Dockerfile.postgres
#    environment:
#      POSTGRES_DB: medcheck
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: Orozali2003
#
#  spring-app:
#    image: orozali/spring-app
#    build:
#      context: .
#      dockerfile: Dockerfile
#    depends_on:
#      - postgres
#    ports:
#      - "8080:8080"
